### ISSUE TITLE
Ops View don't show CPU/RAM usage on OKD/OpenShift

### ISSUE THREAD

**Issue by morsik** [hjacobs/kube-ops-view#182] opened 2018-11-05 11:25 UTC
This is becuase [hardcoded URL](https://github.com/hjacobs/kube-ops-view/blob/d2ff09725406ad93eaaf8d16247dec557799670d/kube_ops_view/kubernetes.py#L104) for checking Heapster stats:

```python
response = request(cluster, '/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes')
```

But instead, OKD/OpenShift uses `openshift-infra` namespace.

Since noone knows if it won't change in future, maybe it should be easier to make configurable namespace where Heapster lives?

**Comment by hjacobs** [comment] 2018-11-05 15:05
Yes, we should fix this :smile: . This is a duplicate of #137.

**Closed by hjacobs** 2018-11-05 15:05 UTC
